travis:
  secure:
    BINSTAR_TOKEN: ZY640aNdlmaMzM+ed+i7DylI3jNwgWd1KojAgvuwpGkYGsqc8ijfXKad+HFWsbOMSlVlnt7JDNqgViKp5ddRZzv1qB956zkHXaD2YQFwlwWGo7Xf1foyK5aLwKUsm4ouCwoeVlYC35zCGwc97l/UwfVzb0ssZ5QL2lXwwzdePDa4GvSE0ScTCE47j/58Y0rqf9iWipd3H95aBqWMu62n4AnmBTZSN/MVOTg0GQ1dtmrmjSQOd+VdsrpqG7BuLk0i0i+RrHYebVXfRIc7ukHn9w5CEC8MfU1K2jIEB8xndJC8hK8tpAFeVTTYtJsIgNq2cXUYiRB7+EeBiWCZ9SqcmnYxdPWKZkWQbfHiB8tyO3aBdT5fx/Mww/YoPY5GSxa8vYVHtGrJhqRJGVHkNcAkyLWwIYMFyTOCA9385zxCQ330YgU9gQmDtfMmqUGwmvHP7OLB4YfRkPfFCbJd1iSWHF27W94OXN8v/svSyN71vTgNxNDr9/zY7hfeQG+WPQBocE3+eZscbGbtkFPavYzd5X4nmExaAPnaxZ5gddPsm7qXvpEgcy3o0UXLeCCIpP7b3koroFVHRu0irxAVl1qwcFxrbNcCQx2uQgFetYnJ6q+u6XEOUZRb5I8DV6FBt4IrACT30J2gSsMcwdoVU/9pNgKalCpOZ3tnOjf/7fjEpCE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
